[package]
name = "imagine"
version = "0.1.0"
edition = "2021"

[dependencies]
image = "0.24.8"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.druid]
version = "0.8.3"
features = ["im", "svg", "image", "gtk"]
